### ISSUE TITLE
Doesn't work with Rails Engines

### ISSUE THREAD

**Issue by jeyb** [Compass/compass-rails#107]
There was a similar problem discussed https://github.com/Compass/compass-rails/issues/88 but this doesn't seem to solve my issue. The solution provided there is for sprite load path.

I have a Rails 3.2.15 app. There is no mention of compass-rails or sass-rails within this application Gemfile. Within `vendor/engines` I have a Rails engine that has the following in the gemspec.

```
s.add_dependency "compass-rails", "~> 2.0.alpha.0"
s.add_dependency "sass-rails", ">= 3"
```

The Rails engine is included in the Gemfile of the main application. Therefore the Gemfile.lock includes compass-rails and sass-rails as one would expect. However I believe there is an issue with load paths as `@import compass/css3` fails with:

```
Sass::SyntaxError: File to import not found or unreadable: compass/css3
Load path: Sass::Rails::Importer(/Users/jeyb/code/app_name/app/assets/stylesheets/application.css.sass)
```

**Comment by ghepting** [comment]
For others that stumble on this recently, the namespace is `Compass::Core::SassExtensions::Functions::InlineImage` in later versions of Compass (`1.0`+?)

**Comment by braindeaf** [comment]
I have the same or very similar problem. I have a Rails 'gem 'rails', github: "rails/rails", branch: "3-2-stable"' app, which loads an Engine which contains most of the functionality of our app. We've configured the Engine so that it is a bootable Rails app and it loads compass fine.

  compass (= 0.12.6)
  compass-rails (= 1.1.7)
  sass (= 3.2.19)
  sass-rails (= 3.2.6)

However, when we load this engine from another parent app using the same Gemfile as the Engine we get the error.  Sass::SyntaxError: File to import not found or unreadable: compass

I've tired as many solutions as I have seen on the multiple issues with similar side effects, requiring 'rails-engine' in engine.rb, Setting the project_path within the engine and in an initializer but nothing.

A few puts inside ImportNode#import show that load_paths do not include the compass directories...

      private

      def import
        paths = @options[:load_paths]
        puts @options[:filename]
        puts paths.to_yaml
        puts @options[:importer].to_yaml
        puts "----"

- /Users/rl/repos/project/vendor/gems/project/app/assets/stylesheets/frontend_root.sass
---
- !ruby/object:Sass::Importers::Filesystem
  root: "/Users/rl/repos/pledge_music"
  same_name_warnings: !ruby/object:Set
    hash: {}
--- !ruby/object:Sass::Importers::Filesystem
root: "/Users/rl/repos/project"
same_name_warnings: !ruby/object:Set
  hash: {}

- /Users/rl/repos/project/vendor/gems/project/app/assets/stylesheets/root_tree.sass
---
- !ruby/object:Sass::Importers::Filesystem
  root: "/Users/rl/repos/project"
  same_name_warnings: !ruby/object:Set
    hash: {}
--- !ruby/object:Sass::Importers::Filesystem
root: "/Users/rl/repos/project"
same_name_warnings: !ruby/object:Set
  hash: {}
Error compiling asset frontend.css:
Sass::SyntaxError: File to import not found or unreadable: compass.
Load path: /Users/rl/repos/project
  (in /Users/rl/repos/project/vendor/gems/engine/app/assets/stylesheets/frontend_root.sass)

Not sure where to go from here. Any ideas?

**Comment by ami1906** [comment]
I was trying to use compass-rails and i am running into issues with inline-images. Previously i was using compass and everything seems to work fine. But now inline-image function is not working. How to get it work with compass-rails. Any suggestions?
