### ISSUE TITLE
*= require #(Third-Party) vs. Compass

### ISSUE THREAD

**Issue by frnco** [Compass/compass-rails#193]
My current Issue happens to be with Gritter, but it's about third-party requires.

Specifically, this line:

    *= require gritter

It works on Development from `application.css.scss`, doesn't work on Production, I got called to help figure out why.

I noticed you guys say it's a horrible idea to `require` from `scss` files, and since `application.css` may be used to require other compass stuff, I figured it could be a nice place to put it.

Still didn't work.

Tried using assets pipeline, `compass compile`, everything I could think of besides copying and pasting gritter's css.

Yet, no solution. I can make everything else work, but I can't compile third-party CSS for the love of it, so I'd like to ask you guys:

1. Is there a way to compile third-party CSS?
2. What about we document it? I can't be the first person with this problem, and I'm certain I won't be the last.

**Comment by craigmcnamara** [comment]
Is this an asset in a gem?

**Comment by craigmcnamara** [comment]
Compass rails is primarily concerned with supporting the rails asset pipeline. If you have some 3rd party CSS/SCSS you should probably be using SASS `@import` as mentioned in the README instead of the asset pipeline directives. If the stylesheet is in a gem as long as it's in `app/assets/stylesheets`, `vendor/assets/stylesheets` or any other path that is configured to be processed by the asset pipeline you should be good. Per the rails docs `require` declarations are processed in isolation from each other so if you want to import something for other sheets to use you should use `@import`.
